---
sidebar: sidebar 
permalink: task_setting_up_cloud_manager.html 
keywords:  
summary: Você pode começar a criar sistemas Cloud Volumes ONTAP logo após implantar o Cloud Manager. No entanto, você pode querer executar uma configuração adicional primeiro configurando o AWS Key Management Service, instalando um certificado HTTPS e muito mais. 
---
= Configuração do Cloud Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode começar a criar sistemas Cloud Volumes ONTAP logo após implantar o Cloud Manager. No entanto, você pode querer executar uma configuração adicional primeiro adicionando contas de provedores de nuvem, configurando o AWS Key Management Service, instalando um certificado HTTPS e muito mais.

* link:task_adding_cloud_accounts.html["Adicionando contas de provedores de nuvem ao Cloud Manager"]
* link:task_adding_nss_accounts.html["Adicionar contas do site de suporte da NetApp ao Cloud Manager"]
* link:task_installing_https_cert.html["Instalar um certificado HTTPS"]
* link:task_setting_up_users_tenants.html["Configuração de usuários e locatários"]
* link:task_setting_up_kms.html["Configurando o AWS KMS"]

